#!/bin/sh
set -e

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
cleanCase0
rm -rf postProcessing
rm -rf debugElmerToFoamBC
rm -rf logs
touch case.foam

restore0Dir

runApplication blockMesh
runApplication checkMesh
runApplication changeDictionary
runApplication elmerToFoamBC
runApplication $(getApplication)
paraFoam -touch
runApplication foamLog log.$(getApplication)
python3 plotResiduals.py

#------------------------------------------------------------------------------
