sim_name: 15-kg_AC-I-eff=30A
visualize: False

# make changes to definitions in config_geo, config_mat, config_sim here!
# config_update:
#   geometry:
#     mesh:
#       size_factor: 1.5
  # simulation:
  #   kristmag_f1:
  #     frequency: 200
  #     side_top:
  #       current_dty: 0  # = 0 A *sqrt(2) / 3.6e-4 m^2
  #       phase: 0  # deg
  #     side_mid:
  #       current_dty: 0  # = 0 A *sqrt(2) / 3.6e-4 m^2
  #       phase: 0  # deg
  #     side_bot:
  #       current_dty: 0  # = 0 A *sqrt(2) / 3.6e-4 m^2
  #       phase: 0  # deg
  #     bot:
  #       current_dty: 0  # = 0 A *sqrt(2) /  2.8e-4 m^2
  #       phase: 0  # deg
  # materials:
    # si-liquid:
    #   Heat Conductivity: 124  # = 62*2
    # CBCF-15:
    #   Emissivity: 0.6
      # Heat Conductivity:  |  # Vacuum
      #   variable Temperature
      #     Real
      #       773.15  0.18
      #       1273.15  0.31
      #       2273.15   0.83
      #     End
    # steel-1.4541:
    #   Emissivity: 0.1  # 200°C
# Uncomment this for parameter study
# study_params:
  # geometry:
  #   mesh:
  #     order: [1, 2]
