general:
  heat_control: True
  heat_convection: True
  heating_induction: True
  phase_change: True
  v_pull: 0.25

boundaries:
  crucible_outside:
    htc: 0  # vacuum
    T_ext: 293.15
  crystal:
    htc: 0  # vacuum
    T_ext: 293.15
  melt:
    htc: 0  # vacuum
    T_ext: 293.15
  inductor_inside:
    T: 293.15
  vessel_outside:
    T: 293.15

heating_induction:
  frequency: 13.5e+3  # Hz
  current: 100  # A
  solver: mgdyn  # statmag is default, alternative: mgdyn

heating_resistance:
  power: 100

smart-heater:
  T: 505  # melting point tin
  control-point: False  # if False: use T at melt-crystal interface (triple point)
  x: 0.035
  y: 0.005
  z: 0.0

solver-update:
#   global:
#     Steady State Max Iterations: 3
  all-solvers:
      Linear System Iterative Method: Idrs
    # Steady State Convergence Tolerance: 1.e-6
    # Nonlinear System Convergence Tolerance: 1.0e-4
    # Linear System Convergence Tolerance: 1.e-9
  # other options: solver-heat, solver-statmag, solver-phase-change

probes:
  crc-wall: [0.055, 0.02]  # Pt100, thermocouples
  crc-wall+2: [0.055, 0.04]  # Wall top surface
  crc-wall+1: [0.055, 0.03]
  crc-wall-1: [0.055, 0.01]
  crc-wall-2: [0.055, 0.00]
  crc-wall-3: [0.055, -0.01]  # Wall bottom surface
  crc-bt: [0.0, -0.01]
  melt-side: [0.048, 0.002]  # Thermocouple through crucible into melt
  melt-control: [0.035, 0.005]  # Temperature control Pt100 / thermocouple
  # base setup: height of meniscus (y-coordinate): 0.03363932
  p1_crys_in: [0, 0.05863932]  # base setup: center of crystal at l/4
  p1_crys_sf: [0.004, 0.05863932]  # base setup: surface of crystal at l/4
  p2_crys_in: [0, 0.08363932]  # base setup: center of crystal at l/2
  p2_crys_sf: [0.004, 0.08363932]  # base setup: surface of crystal at l/2
  p3_crys_in: [0, 0.10863932]  # base setup: center of crystal at 3l/4
  p3_crys_sf: [0.004, 0.10863932]  # base setup: surface of crystal at 3l/4
  p4_crys_tp: [0, 0.13363932]  # base setup: interface between seed & crystal
  p5_seed: [0.0009, 0.14363932]  # base setup: center of seed at l/4
  p6_seed: [0.0009, 0.15363932]  # base setup: center of seed at l/2
  p7_seed: [0.0009, 0.16363932]  # base setup: center of seed at 3l/4
  p8_seed: [0.0009, 0.17363932]  # base setup: center of seed at l

save_line_solver:
  Exec Solver: 'After timestep'
  Equation: '"SaveLine"'
  Procedure: '"SaveData" "SaveLine"'
  Filename: '"save_lines.dat"'
  Output Directory: './results'
  Variable 1: temperature
  Variable 2: temperature grad 1
  Variable 3: temperature grad 2

FluxSolver:
  Exec Solver: 'after timestep'
  Equation: 'String "Flux Solver"'
  Procedure: '"FluxSolver" "FluxSolver"'
  Calculate Grad: 'Logical True'
  Calculate Flux: 'Logical True'
  Target Variable: 'String "Temperature"'
  Flux Coefficient: 'String "Heat Conductivity"'
  Linear System Solver: '"Iterative"'
  Linear System Convergence Tolerance: 1.0e-8
  Linear System Iterative Method: '"BiCGStab"'
  Linear System Max Iterations: 500
  Linear System Preconditioning: ILU
  Linear System Residual Output: 0

GmshInput:
  Exec Solver: before simulation
  Equation: GmshInput
  Procedure: '"GmshOutputReader" "GmshOutputReader"'
  Output Directory: "."
  Filename: File "of_result.msh"

