functions:
  - |
    $function heatconty(x) {_heatconty = (3.936284e-01 + 2.332041e-03 * (x- 273.15)^1 + -2.855198e-06 * (x- 273.15)^2 + 1.482131e-09 * (x- 273.15)^3) 0 \
                                            0 (9.111736e-02 + 3.878800e-04 * (x- 273.15)^1 + -2.752193e-07 * (x- 273.15)^2 + 1.942076e-10 * (x- 273.15)^3)}

air:
  Density: 1.1885  # 20°C
  Electric Conductivity: 0.0 
  Heat Capacity: 1006.4  # 20°C
  Heat Conductivity: 25.873e-3  # 20°C
  Relative Permeability: 1
  Relative Permittivity: 1
aluminum:
  Density: 2700
  Heat Capacity: 984
  Heat Conductivity: 236  
  Emissivity: 0.05  
  Electric Conductivity: 3.7e+7
  Relative Permeability: 1
  Relative Permittivity: 1
bismuth-liquid:
  Density: 10050
  Electric Conductivity: 7.68e+5
  Emissivity: 0.366  # set equal to solid
  Heat Capacity: 146.3
  Heat Conductivity: 10.23
  Relative Permeability: 1
  Relative Permittivity: 1
  Liquid: 'Logical True'
  Surface Tension: 0.378
bismuth-solid:
  Density: 9832
  Electric Conductivity: 3.44e+5
  Emissivity: 0.366
  Heat Capacity: 147
  Heat Conductivity: 7.5
  Relative Permeability: 1
  Relative Permittivity: 1
  Solid: 'Logical True'
  Melting Point: 544.1
  Latent Heat: 5.21e+4  # J / kg
copper-inductor:
  Density: 8960.0  # 0°C
  Electric Conductivity: 0.0  # necessary for 2D
  Emissivity: 0.2  # 327°C
  Heat Capacity: 384.4  # interpolated for 20°C
  Heat Conductivity: 390.0  # estimated using data sheets
  Relative Permeability: 1
  Relative Permittivity: 1
copper-seed:
  Density: 8960.0  # 0°C
  Electric Conductivity: 32.3e+6  # 200°C
  Emissivity: 0.2  # 327°C
  Heat Capacity: 415.0  # 200°C
  Heat Conductivity: 390.0  # estimated using data sheets
  Relative Permeability: 1
  Relative Permittivity: 1
graphite-CZ3R6300:  # crucible, adapter
  Density: 1730.0
  Electric Conductivity: 5.88e+4
  Emissivity: 0.7  # estimate based on own measurements
  Heat Capacity: 1237.0
  Heat Conductivity: 65  # 20°C
  Relative Permeability: 1
  Relative Permittivity: 1
insulation:
  Density: 220.0
  Electric Conductivity: 1.95e+2
  Emissivity: 0.7  # 250°C
  Heat Capacity: 1237.0
  # Heat Conductivity: 0.2
  # Heat Conductivity (2, 2): |  # Measurement, approx 300°C
  #     Real \
  #     0.9    0 \
  #     0    0.2
  Heat Conductivity (2, 2): |  # measurement, defined above in "functions" section
    variable temperature
        MATC "heatconty(tx)"
  Relative Permeability: 1
  Relative Permittivity: 1
steel-1.4541:
  Density: 7900.0  # 20°C
  Electric Conductivity: 1.37e+6  # 20°C
  Emissivity: 0.2  # 200°C
  Heat Capacity:  470.0 # 20°C
  Heat Conductivity: 15.0 # 20°C
  Relative Permeability: 1
  Relative Permittivity: 1
tin-liquid:
  Density: 6980.0
  Electric Conductivity: 2.08e+6
  Emissivity: 0.064  # set equal to solid
  Heat Capacity: 252.7
  Heat Conductivity: 29.0
  Relative Permeability: 1
  Relative Permittivity: 1
  Liquid: 'Logical True'
  Surface Tension: 0.56
  Beta: 10  # Deg
tin-solid:
  Density: 7179.0
  Electric Conductivity: 4.38e+6
  Emissivity: 0.064
  Heat Capacity: 244.0
  Heat Conductivity: 60.0
  Relative Permeability: 1
  Relative Permittivity: 1
  Solid: 'Logical True'
  Melting Point: 505
  Latent Heat: 5.96e+4  # J / kg
vacuum:  # equals air with reduced density, conductivity
  Density: 1.1885e-9
  Electric Conductivity: 0.0 
  Heat Capacity: 1006.4
  Heat Conductivity: 1.0e-10
  Relative Permeability: 1
  Relative Permittivity: 1
