# Configuration of simulation

sim_name: csi-exp-2_5mm-steps
visualize: False

# make changes to definitions in config_geo, config_mat, config_sim here!
# config_update:
  # materials:
  #   csi-solid:
  #     Emissivity: 0.5
    # csi-liquid:
    #   Heat Conductivity: 2.5
  #     Emissivity: 0.5
  # simulation:
  #   general:
  #     v_pull: 0.2
  # geometry:
  #   crystal:
  #     current_length: 0.035

  # simulation:
  #   boundaries:
  #     crystal:
  #       htc: 0  # vacuum
  #       # htc: 10  # air
  #       # htc: 35  # fan
  #     crucible_outside:
  #       htc: 0  # vacuum
  #       # htc: 10  # air
  #       # htc: 16  # fan
  #     melt:
  #       htc: 0  # vacuum
  #       # htc: 10  # air
  #       # htc: 16  # fan
  # geometry:
  #   filling:
  #     material: vacuum

quasi_transient:
  - length: 0.00  # m
    v_pull: 0.2 # mm/min
  # - length: 0.001  # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.002  # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.003 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.004 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.005 # m
    v_pull: 0.2 # mm/min
  # - length: 0.006 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.007 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.008 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.009 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.010 # m
    v_pull: 0.2 # mm/min
  # - length: 0.011 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.012 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.013 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.014 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.015 # m
    v_pull: 0.2 # mm/min
  # - length: 0.016 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.017 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.018 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.019 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.020 # m
    v_pull: 0.2 # mm/min
  # - length: 0.021 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.022 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.023 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.024 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.025 # m
    v_pull: 0.2 # mm/min
  # - length: 0.026 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.027 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.028 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.029 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.030 # m
    v_pull: 0.2 # mm/min
  # - length: 0.031 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.032 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.033 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.034 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.035 # m
    v_pull: 0.2 # mm/min
  # - length: 0.036 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.037 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.038 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.039 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.040 # m
    v_pull: 0.2 # mm/min
  # - length: 0.041 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.042 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.043 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.044 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.045 # m
    v_pull: 0.2 # mm/min
  # - length: 0.046 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.047 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.048 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.049 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.050 # m
    v_pull: 0.2 # mm/min
  # - length: 0.051 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.052 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.053 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.054 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.055 # m
    v_pull: 0.2 # mm/min
  # - length: 0.056 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.057 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.058 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.059 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.060 # m
    v_pull: 0.2 # mm/min
  # - length: 0.061 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.062 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.063 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.064 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.065 # m
    v_pull: 0.2 # mm/min
  # - length: 0.066 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.067 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.068 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.069 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.070 # m
    v_pull: 0.2 # mm/min
  # - length: 0.071 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.072 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.073 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.074 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.075 # m
    v_pull: 0.2 # mm/min
  # - length: 0.076 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.077 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.078 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.079 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.08 # m
    v_pull: 0.2 # mm/min
  # - length: 0.081 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.082 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.083 # m
  #   v_pull: 0.2 # mm/min
  # - length: 0.084 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.085 # m
    v_pull: 0.2 # mm/min
  # - length: 0.086 # m
  #   v_pull: 0.2 # mm/min
  - length: 0.087 # m
    v_pull: 0.2 # mm/min

# # Uncomment this for parameter study
# # study_params:
# #   simulation:
# #     heating_induction:
# #       solver: [statmag, mgdyn]
# #   geometry:
# #     crystal:
# #       # current_length: [0.001, 0.002, 0.003, 0.004, 0.005]  # vpull = 0.1 mm/min
